(require 'mongodb)

(let ((mongo-process (mongodb-shell-start "mongodb://localhost:27017/woooo")))
  (message "==============")
  (with-current-buffer (get-buffer-create "*mongo-scratch*")
    (erase-buffer)
    ;; (message (mongodb-shell-topology-type mongo-process))
    (insert (format "%S" (mongodb-shell-list-collections mongo-process "admin")) "\n")
    (insert (format "%S" (mongodb-shell-command mongo-process "db.blah.find()")) "\n")
    (insert (format "%S" (mongodb-shell-command mongo-process "use blah")) "\n")
    (insert (format "%S" (mongodb-shell-command mongo-process "db.blah.insertOne({})")) "\n")
    (insert (format "%S" (mongodb-shell-command mongo-process "db.blah.find()")) "\n")
    ;; (insert (mongodb-shell-get-topology mongo-process))
    (mongodb-shell-command mongo-process "exit")
    ))
